### ISSUE TITLE
Doesn't run the first time.

### ISSUE THREAD

**Issue by FrakGart** [basnijholt/rsync-time-machine.py#20]
When I try to run `rsync-time-machine` the first time it dies on line 284 because there are no existing backups.

I put a dirty hack in to return after `backups = find_backups(dest_folder, ssh)` if nothing was returned and I could get it to do the first backup.

**Comment by basnijholt** [comment]
Thanks opening this issue. Do you mind sharing the entire error message?

**Comment by FrakGart** [comment]
```Traceback (most recent call last):
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\Scripts\rsync-time-machine.exe\__main__.py", line 7, in <module>
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\rsync_time_machine.py", line 900, in main
    backup(
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\rsync_time_machine.py", line 854, in backup
    expire_backups(
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\rsync_time_machine.py", line 284, in expire_backups
    oldest_backup_to_keep = sorted(backups)[0]
IndexError: list index out of range
```

**Comment by basnijholt** [comment]
Ah I see. I think it is very likely that it is because of Windows.

The code should never even reach that line if there are no backups. This means something else must go wrong.

Are you using WSL or the Windows Command Line directly?

**Comment by FrakGart** [comment]
This was running it in Cygwin. 

Running in WSL works the first time you use it.
